import "~/styles/globals.css";

import { TopMenu } from "../components/topMenu/TopMenu";
import * as data from '../data'
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {

  return (
      <div className="page">
        {children}
      </div>
  );
}
